import type { Product } from './types';

export const allProducts: Product[] = [
    {
        id: 17586,
        name: "Tratamiento de Día Rico SPF 30 Multi-Active",
        brand: "Nove Age",
        price: 62.00,
        regularPrice: 120.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2019/06/productImage-pach-nove-age-multi-active-ageing-1.webp`,
        description: "Un tratamiento de día rico y nutritivo que protege la piel con SPF 30 mientras combate los signos del envejecimiento. Ideal para una piel hidratada y protegida durante todo el día.",
        stock: 25,
        category: 'skincare',
        rating: 5,
        reviewCount: 112,
    },
    {
        id: 20378,
        name: "After Sun Jelly",
        brand: "SunCare",
        price: 14.00,
        regularPrice: 17.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2019/06/productImage-9.webp`,
        description: "Calma y refresca tu piel después de la exposición al sol. Este gel ligero hidrata y repara, dejando una sensación de confort inmediato.",
        stock: 40,
        category: 'personal-care',
        rating: 4,
        reviewCount: 78,
    },
    {
        id: 20374,
        name: "Caja de Regalo Crema Universal",
        brand: "Tender Care",
        price: 17.00,
        regularPrice: 19.99,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2025/11/48648_1.jpeg`,
        description: "El regalo perfecto. Este set incluye tres versiones de la icónica Crema Universal: Original, Fruta de la Pasión y una edición especial. Hidratación y cuidado para labios, codos y más.",
        stock: 50,
        category: 'skincare',
        rating: 5,
        reviewCount: 210,
    },
    {
        id: 17583,
        name: "Champú Matizador Rubios y Grises",
        brand: "DUOLOGI",
        price: 8.49,
        regularPrice: 14.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2019/10/1000012413.jpg`,
        description: "Neutraliza los tonos amarillentos no deseados en cabellos rubios, con mechas o grises. Su fórmula con pigmentos violetas deja el color vibrante y el cabello suave.",
        stock: 35,
        category: 'hair',
        rating: 4,
        reviewCount: 65,
    },
     {
        id: 19084,
        name: "Champú Protector del Color",
        brand: "DUOLOGI",
        price: 12.00,
        imageUrl: 'https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2025/10/DUOLOGI-Colour-Protect-Shampoo-4-600x600-1.jpg',
        description: "Limpia suavemente mientras protege la vitalidad de tu cabello teñido. Ayuda a sellar el color, previene la decoloración y aporta un brillo radiante.",
        stock: 30,
        category: 'hair',
        rating: 4,
        reviewCount: 55,
    },
    {
        id: 19103,
        name: "Champú Purificante y Exfoliante Anticaspa",
        brand: "DUOLOGI",
        price: 14.50,
        imageUrl: 'https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2025/10/CHAMPU-PURIFICANTE-Y-EXFOLIANTE-CUERO-CABELLUDOI.webp',
        description: "Una solución completa para el cuero cabelludo. Exfolia suavemente para eliminar la caspa y las impurezas, dejando una sensación de frescor y limpieza duradera.",
        stock: 22,
        category: 'hair',
        rating: 5,
        reviewCount: 48,
    },
    {
        id: 17885,
        name: "Corrector y Serum Potenciador Giordani Gold",
        brand: "Giordani Gold",
        price: 7.49,
        regularPrice: 24.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2025/10/serum-potenciador-y-corrector-giordany-gold-1.webp`,
        description: "Un producto híbrido que combina la cobertura de un corrector con los beneficios de un serum. Ilumina la mirada, disimula imperfecciones y cuida la delicada piel del contorno de ojos.",
        stock: 45,
        category: 'makeup',
        rating: 5,
        reviewCount: 132,
    },
    {
        id: 1467,
        name: "Crema Corporal Perfumada Divine",
        brand: "Divine",
        price: 8.49,
        regularPrice: 11.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2019/06/productImage-11.webp`,
        description: "Hidrata tu piel y envuélvela en la icónica y poderosa fragancia de Divine. Una crema corporal rica que deja la piel suave, nutrida y delicadamente perfumada.",
        stock: 60,
        category: 'personal-care',
        rating: 4,
        reviewCount: 98,
    },
    {
        id: 1440,
        name: "Crema Corporal Perfumada Essenza Supreme",
        brand: "Giordani Gold",
        price: 8.49,
        regularPrice: 14.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2019/06/productImage-12.webp`,
        description: "Una lujosa crema corporal que hidrata profundamente y deja en la piel la sofisticada fragancia floral amaderada de Giordani Gold Essenza Supreme.",
        stock: 50,
        category: 'personal-care',
        rating: 5,
        reviewCount: 105,
    },
    {
        id: 19916,
        name: "Eau de Toilette Every Me Sweetheart Rose",
        brand: "Every Me",
        price: 18.47,
        regularPrice: 23.99,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2025/10/Eau-de-Toilette-Every-Me-Sweetheart-Rose.webp`,
        description: "Una fragancia juguetona y floral que combina delicada agua de rosas y peonía con jugoso lichi y almizcle. El aroma perfecto para tu lado más dulce y romántico.",
        stock: 33,
        category: 'perfume',
        rating: 4,
        reviewCount: 45,
    },
    {
        id: 42352,
        name: "Gel Limpiador Refrescante",
        brand: "NovAge",
        price: 17.99,
        regularPrice: 31.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2019/06/Gel-Limpiador-Refrescante.webp`,
        description: "Un gel limpiador refrescante que elimina impurezas y maquillaje, dejando la piel limpia, suave y revitalizada sin resecar.",
        stock: 50,
        category: 'skincare',
        rating: 5,
        reviewCount: 95,
    },
    {
        id: 47494,
        name: "Espuma Limpiadora Skinrelief Pro Resilient NovAge",
        brand: "NovAge",
        price: 18.00,
        regularPrice: 32.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2019/06/Espuma-Limpiadora-Skinrelief-Pro-Resilient-NovAge2.webp`,
        description: "Espuma limpiadora suave diseñada para pieles sensibles. Calma, limpia y ayuda a fortalecer la barrera cutánea gracias a su tecnología Pro-Resilient.",
        stock: 30,
        category: 'skincare',
        rating: 5,
        reviewCount: 88,
    },
    {
        id: 43243,
        name: "Maquillaje Eternal Glow SPF 25 Giordani Gold",
        brand: "Giordani Gold",
        price: 17.99,
        regularPrice: 32.00,
        imageUrl: `https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43243%2FES%2F43243_1.png`,
        description: "Base de maquillaje con serum que ilumina y perfecciona la piel al instante y a largo plazo. Con SPF 25 y Ácido Hialurónico para un acabado radiante y juvenil.",
        stock: 40,
        category: 'makeup',
        subCategory: 'Giordani Gold',
        rating: 5,
        reviewCount: 953,
        variants: {
            Tono: [
                { value: 'Light Ivory', colorCode: '#F5E4D3' },
                { value: 'Porcelain', colorCode: '#F3D9C6' },
                { value: 'Warm Beige', colorCode: '#E4BFA8' },
                { value: 'Natural Sand', colorCode: '#D8AF92' },
                { value: 'Golden Sun', colorCode: '#C89A76' },
            ]
        }
    },
    {
        id: 104,
        name: "WellnessPack Mujer Wellosophy",
        brand: "Wellosophy",
        price: 45.00,
        imageUrl: `https://raw.githubusercontent.com/tmaromero/imagenes/main/29696.png`,
        description: "Cuida tu bienestar integral con WellnessPack Mujer de Wellosophy. Cada sobre diario te aporta una mezcla precisa de 12 vitaminas, 10 minerales, Omega-3 de alta calidad y potentes antioxidantes como la Astaxantina.",
        stock: 20,
        category: 'wellness',
        rating: 5,
        reviewCount: 210,
    },
    {
        id: 103,
        name: "Pre-Champú Reparador Duologi",
        brand: "DUOLOGI",
        price: 13.00,
        imageUrl: `https://raw.githubusercontent.com/tmaromero/imagenes/main/44960.png`,
        description: "Transforma tu cabello con el Pre-Champú Reparador Duologi. Este tratamiento intensivo prelavado penetra en la fibra capilar para reparar y reducir el daño visible desde la primera aplicación.",
        stock: 25,
        category: 'hair',
        rating: 4,
        reviewCount: 45,
    },
    {
        id: 102,
        name: "Maquillaje Everlasting Sync SPF 20",
        brand: "THE ONE",
        price: 18.00,
        imageUrl: `https://raw.githubusercontent.com/tmaromero/imagenes/main/42128.png`,
        description: "Descubre el maquillaje inteligente que se sincroniza con tu piel. La Base Everlasting Sync SPF 20 de THE ONE, con Tecnología Skin Response, se adapta a la humedad del ambiente para un acabado fresco y semi-mate que dura hasta 30 horas.",
        stock: 30,
        category: 'makeup',
        subCategory: 'THE ONE',
        rating: 5,
        reviewCount: 150,
    },
    {
        id: 46901,
        name: "Perlas con Serum Giordani Gold - Edición Especial",
        brand: "Giordani Gold",
        price: 21.99,
        regularPrice: 35.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46901%2F46901_1.png",
        description: "Perlas de color con serum rejuvenecedor que aportan color, rubor y luminosidad. Edición especial con un diseño exclusivo para un acabado radiante y juvenil.",
        stock: 25,
        category: 'makeup',
        subCategory: 'Giordani Gold',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 1,
    },
    {
        id: 47828,
        name: "Brocha Blush & Glow",
        brand: "Vellaperfumeria",
        price: 6.49,
        regularPrice: 11.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47828%2F47828_1.png",
        description: "Brocha de maquillaje de alta calidad, perfecta para aplicar colorete e iluminador. Sus cerdas suaves y su forma angulada permiten una aplicación precisa y un acabado profesional.",
        stock: 50,
        category: 'accessories',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 86,
    },
    {
        id: 47949,
        name: "Máscara de Pestañas 5 en 1 Wonder Lash Prom Queen THE ONE",
        brand: "THE ONE",
        price: 6.99,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47949%2F47949_1.png",
        description: "La máscara de pestañas 5 en 1 definitiva, ahora en edición especial Prom Queen. Ofrece longitud, volumen, rizo, separación y cuidado en una sola pasada para una mirada de impacto.",
        stock: 100,
        category: 'makeup',
        subCategory: 'THE ONE',
        rating: 5,
        reviewCount: 878,
    },
    {
        id: 46801,
        name: "Eau de Parfum Divine Dark Velvet",
        brand: "Divine",
        price: 27.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46801%2F46801_1.png",
        description: "Una fragancia sensual y misteriosa con notas de terciopelo oscuro, ideal para la noche.",
        stock: 30,
        category: 'perfume',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 26,
    },
    {
        id: 49145,
        name: "Collar Divine Dark Velvet",
        brand: "Divine",
        price: 29.99,
        regularPrice: 41.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F49145%2F49145_1.png",
        description: "Un collar elegante y sofisticado para complementar tu look, inspirado en la fragancia Divine Dark Velvet.",
        stock: 15,
        category: 'accessories',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 1,
    },
    {
        id: 48075,
        name: "Muestra Eau de Parfum Divine Dark Velvet",
        brand: "Divine",
        price: 1.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48075%2F48075_1.png",
        description: "Prueba la nueva y cautivadora fragancia Divine Dark Velvet con esta muestra.",
        stock: 100,
        category: 'perfume',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 0,
    },
    {
        id: 42041,
        name: "Spray Eau de Parfum Divine - Tamaño Viaje",
        brand: "Divine",
        price: 10.99,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42041%2F42041_1.png",
        description: "Tu fragancia Divine favorita en un práctico formato de viaje para que la lleves siempre contigo.",
        stock: 50,
        category: 'perfume',
        rating: 5,
        reviewCount: 321,
    },
    {
        id: 47016,
        name: "Crema Corporal Perfumada Divine",
        brand: "Divine",
        price: 8.99,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47016%2F47016_1.png",
        description: "Hidratación intensa con el aroma icónico y floral de Divine. Deja tu piel suave y perfumada.",
        stock: 40,
        category: 'personal-care',
        rating: 5,
        reviewCount: 714,
    },
    {
        id: 38497,
        name: "Eau de Parfum Divine",
        brand: "Divine",
        price: 27.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38497%2FES%2F38497_1.png",
        description: "La fragancia floral original de Divine, un clásico que celebra la feminidad y el poder.",
        stock: 35,
        category: 'perfume',
        rating: 5,
        reviewCount: 1953,
    },
    {
        id: 42120,
        name: "Máscara de Pestañas 5 en 1 Wonder Lash Waterproof THE ONE",
        brand: "THE ONE",
        price: 6.99,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42120%2F42120_1.png",
        description: "Todos los beneficios de la máscara 5 en 1, ahora con una fórmula resistente al agua para una duración impecable.",
        stock: 80,
        category: 'makeup',
        subCategory: 'THE ONE',
        rating: 5,
        reviewCount: 841,
    },
    {
        id: 43123,
        name: "Máscara de Pestañas 5 en 1 Wonder Lash Ultra THE ONE",
        brand: "THE ONE",
        price: 6.99,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43123%2F43123_1.png",
        description: "Lleva tus pestañas al siguiente nivel con la versión Ultra, que ofrece un volumen y definición extremos.",
        stock: 75,
        category: 'makeup',
        subCategory: 'THE ONE',
        rating: 5,
        reviewCount: 613,
    },
    {
        id: 46319,
        name: "Niacinamida 10% Power Drops Proceuticals Novage+",
        brand: "Novage+",
        price: 39.99,
        regularPrice: 57.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46319%2F46319_1.png",
        description: "Tratamiento concentrado con Niacinamida al 10% que minimiza los poros, unifica el tono y fortalece la barrera cutánea.",
        stock: 20,
        category: 'skincare',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 3,
    },
    {
        id: 47267,
        name: "Jabón Líquido con Flor de Loto y Madera de Cedro",
        brand: "Essense&Co.",
        price: 14.99,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47267%2F47267_1.png",
        description: "Lujoso jabón líquido para manos y cuerpo con una fragancia relajante de flor de loto y madera de cedro.",
        stock: 60,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 141,
    },
    {
        id: 47268,
        name: "Loción Hidratante con Flor de Loto y Madera de Cedro",
        brand: "Essense&Co.",
        price: 15.99,
        regularPrice: 21.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47268%2F47268_1.png",
        description: "Loción hidratante para manos y cuerpo que deja la piel suave y delicadamente perfumada con notas de loto y cedro.",
        stock: 55,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 115,
    },
    {
        id: 153753,
        name: "Lote Essense & Co",
        brand: "Essense&Co.",
        price: 22.99,
        regularPrice: 41.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F153753%2F153753_1.png",
        description: "Un set de lujo que incluye el jabón líquido y la loción hidratante de la línea Essense & Co.",
        stock: 25,
        category: 'personal-care',
        tag: 'NOVEDAD',
        statusLabel: 'Set',
        rating: 5,
        reviewCount: 0,
    },
    {
        id: 18437,
        name: "Tratamiento Restaurador de Noche Diamond Cellular",
        brand: "Diamond Cellular",
        price: 24.99,
        regularPrice: 57.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F18437%2FES%2F18437_1.png",
        description: "Tratamiento de noche de alto rendimiento que ayuda a regenerar y rejuvenecer la piel mientras duermes.",
        stock: 30,
        category: 'skincare',
        rating: 5,
        reviewCount: 1327,
    },
    {
        id: 21339,
        name: "Solución Micelar Diamond Cellular",
        brand: "Diamond Cellular",
        price: 18.99,
        regularPrice: 29.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F21339%2FES%2F21339_1.png",
        description: "Un limpiador multifuncional que elimina maquillaje, tonifica y calma la piel en un solo paso.",
        stock: 40,
        category: 'skincare',
        rating: 5,
        reviewCount: 1798,
    },
    {
        id: 13659,
        name: "Crema Antienvejecimiento Diamond Cellular",
        brand: "Diamond Cellular",
        price: 28.99,
        regularPrice: 57.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F13659%2FES%2F13659_1.png",
        description: "Crema de día de lujo que combate los signos del envejecimiento para una piel visiblemente más joven.",
        stock: 28,
        category: 'skincare',
        rating: 5,
        reviewCount: 3154,
    },
    {
        id: 47421,
        name: "Espátula de Crema Hidratante Oriflame Exklusiv",
        brand: "Oriflame Exklusiv",
        price: 5.29,
        regularPrice: 6.50,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47421%2F47421_1.png",
        description: "Una espátula higiénica para aplicar tus cremas faciales, evitando la contaminación del producto.",
        stock: 100,
        category: 'accessories',
        rating: 5,
        reviewCount: 473,
    },
    {
        id: 47005,
        name: "Crema de Día Reafirmante SPF 20 Royal Velvet",
        brand: "Royal Velvet",
        price: 20.99,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47005%2F47005_1.png",
        description: "Una crema de día que reafirma y redefine el contorno facial, con SPF 20 para proteger la piel.",
        stock: 35,
        category: 'skincare',
        rating: 5,
        reviewCount: 2161,
    },
    {
        id: 47006,
        name: "Crema de Noche Reafirmante Royal Velvet",
        brand: "Royal Velvet",
        price: 20.99,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47006%2F47006_1.png",
        description: "Trabaja durante la noche para fortalecer y reafirmar la piel, reduciendo la apariencia de arrugas.",
        stock: 32,
        category: 'skincare',
        rating: 5,
        reviewCount: 1781,
    },
    {
        id: 47587,
        name: "Pendientes Royal Velvet",
        brand: "Royal Velvet",
        price: 16.99,
        regularPrice: 22.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47587%2F47587_1.png",
        description: "Elegantes pendientes que complementan la lujosa línea de cuidado de la piel Royal Velvet.",
        stock: 20,
        category: 'accessories',
        rating: 4.5,
        reviewCount: 19,
    }
];