import type { Product } from './types';

export const allProducts: Product[] = [
    {
        id: 17586,
        name: "Tratamiento de Día Rico SPF 30 Multi-Active",
        brand: "NovAge+",
        price: 62.00,
        regularPrice: 120.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2019/06/productImage-pach-nove-age-multi-active-ageing-1.webp`,
        description: "Tratamiento de día rico y ultrahidratante formulado para nutrir intensamente y reponer la piel, a la vez que la protege de los agresores urbanos como la polución y los rayos UV. Con factor de protección solar SPF 30.",
        howToUse: "Aplicar por la mañana sobre la piel limpia. Coger una pequeña cantidad de crema de día con la yema de los dedos y masajear suavemente sobre el rostro y el cuello, evitando el contorno de los ojos.",
        stock: 25,
        category: 'skincare',
        rating: 5,
        reviewCount: 112,
    },
    {
        id: 20378,
        name: "After Sun Jelly",
        brand: "SunCare",
        price: 14.00,
        regularPrice: 17.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2019/06/productImage-9.webp`,
        description: "Gelatina after sun para rostro y cuerpo que hidrata intensamente y calma la piel al instante después de la exposición al sol hasta 24 horas. Ayuda a prolongar el bronceado.",
        howToUse: "Aplicar generosamente sobre la piel limpia después de la exposición al sol. Masajear suavemente hasta su completa absorción.",
        stock: 40,
        category: 'personal-care',
        rating: 4,
        reviewCount: 78,
    },
    {
        id: 20374,
        name: "Caja de Regalo Crema Universal",
        brand: "Tender Care",
        price: 17.00,
        regularPrice: 19.99,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2025/11/48648_1.jpeg`,
        description: "El bálsamo multiusos original con cera de abeja natural y vitamina E, en una caja de regalo con tres variantes: Original, Fruta de la Pasión y Arándano Rojo. Suaviza, calma e hidrata la piel seca.",
        howToUse: "Aplicar sobre la piel seca de rostro, labios, manos, codos, rodillas o pies. Usar tantas veces como sea necesario.",
        stock: 50,
        category: 'skincare',
        rating: 5,
        reviewCount: 210,
    },
    {
        id: 17583,
        name: "Champú Matizador Rubios y Grises",
        brand: "DUOLOGI",
        price: 8.49,
        regularPrice: 14.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2019/10/1000012413.jpg`,
        description: "Un champú con pigmentos violetas que neutraliza los tonos cobrizos y amarillentos en cabellos rubios y grises. Limpia suavemente sin resecar, dejando el cabello brillante y con un color vibrante.",
        howToUse: "Aplicar sobre el cabello mojado, masajear hasta crear espuma y dejar actuar de 1 a 3 minutos. Aclarar abundantemente. Usar una o dos veces por semana.",
        stock: 35,
        category: 'hair',
        rating: 4,
        reviewCount: 65,
    },
     {
        id: 19084,
        name: "Champú Protector del Color",
        brand: "DUOLOGI",
        price: 12.00,
        imageUrl: 'https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2025/10/DUOLOGI-Colour-Protect-Shampoo-4-600x600-1.jpg',
        description: "Champú que protege el color del cabello teñido frente a la pérdida de intensidad. Formulado con Filtros UV que prolongan la vida del color y mantienen el cabello brillante.",
        howToUse: "Aplicar sobre el cabello mojado y masajear suavemente hasta crear espuma. Aclarar con abundante agua.",
        stock: 30,
        category: 'hair',
        rating: 4,
        reviewCount: 55,
    },
    {
        id: 19103,
        name: "Champú Purificante y Exfoliante Anticaspa",
        brand: "DUOLOGI",
        price: 14.50,
        imageUrl: 'https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2025/10/CHAMPU-PURIFICANTE-Y-EXFOLIANTE-CUERO-CABELLUDOI.webp',
        description: "Exfoliante capilar que purifica el cuero cabelludo con caspa. Formulado con Ácido Salicílico y Tecnología Dandicontrol que actúa directamente en el origen del problema para un alivio duradero.",
        howToUse: "Aplicar sobre el cuero cabelludo mojado, masajear suavemente y aclarar con abundante agua. Usar en lugar del champú habitual 1 o 2 veces por semana.",
        stock: 22,
        category: 'hair',
        rating: 5,
        reviewCount: 48,
    },
    {
        id: 17885,
        name: "Corrector y Serum Potenciador Giordani Gold",
        brand: "Giordani Gold",
        price: 7.49,
        regularPrice: 24.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2025/10/serum-potenciador-y-corrector-giordany-gold-1.webp`,
        description: "Un producto híbrido que combina la cobertura de un corrector con los beneficios de un serum. Ilumina la mirada, disimula imperfecciones y cuida la delicada piel del contorno de ojos.",
        howToUse: "Aplicar una pequeña cantidad sobre las imperfecciones o en la zona de la ojera. Difuminar suavemente con la yema de los dedos, una brocha o una esponja.",
        stock: 45,
        category: 'makeup',
        productType: 'Corrector',
        subCategory: 'Giordani Gold',
        rating: 5,
        reviewCount: 132,
    },
    {
        id: 1440,
        name: "Crema Corporal Perfumada Essenza Supreme",
        brand: "Giordani Gold",
        price: 8.49,
        regularPrice: 14.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2019/06/productImage-12.webp`,
        description: "Una lujosa crema corporal que hidrata profundamente y deja en la piel la sofisticada fragancia floral amaderada de Giordani Gold Essenza Supreme.",
        howToUse: "Masajear generosamente sobre la piel limpia y seca para hidratar y perfumar. Prestar especial atención a las zonas más secas.",
        stock: 50,
        category: 'personal-care',
        rating: 5,
        reviewCount: 105,
    },
    {
        id: 19916,
        name: "Eau de Toilette Every Me Sweetheart Rose",
        brand: "Every Me",
        price: 18.47,
        regularPrice: 23.99,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2025/10/Eau-de-Toilette-Every-Me-Sweetheart-Rose.webp`,
        description: "Una fragancia juguetona y floral que combina delicada agua de rosas y peonía con jugoso lichi y almizcle. El aroma perfecto para tu lado más dulce y romántico.",
        howToUse: "Vaporizar sobre los puntos de pulso: cuello, muñecas e interior de los codos para que la fragancia dure más tiempo.",
        stock: 33,
        category: 'perfume',
        rating: 4,
        reviewCount: 45,
    },
    {
        id: 42352,
        name: "Gel Limpiador Refrescante",
        brand: "NovAge",
        price: 17.99,
        regularPrice: 31.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2019/06/Gel-Limpiador-Refrescante.webp`,
        description: "Un gel limpiador 2 en 1 con Vitamina E y Glicerina que limpia y tonifica la piel, dejándola suave, radiante y libre de impurezas. Formulado para todo tipo de pieles.",
        howToUse: "Usar por la mañana y por la noche. Humedecer el rostro, aplicar una pulsación del gel y masajear. Aclarar con abundante agua.",
        stock: 50,
        category: 'skincare',
        rating: 5,
        reviewCount: 95,
    },
    {
        id: 47494,
        name: "Espuma Limpiadora Skinrelief Pro Resilient NovAge",
        brand: "NovAge",
        price: 18.00,
        regularPrice: 32.00,
        imageUrl: `https://i0.wp.com/vellaperfumeria.com/wp-content/uploads/2019/06/Espuma-Limpiadora-Skinrelief-Pro-Resilient-NovAge2.webp`,
        description: "Espuma limpiadora suave diseñada para pieles sensibles. Calma, limpia y ayuda a fortalecer la barrera cutánea gracias a su tecnología Pro-Resilient.",
        howToUse: "Aplicar una o dos pulsaciones sobre la piel húmeda. Masajear suavemente con movimientos circulares y aclarar con agua tibia.",
        stock: 30,
        category: 'skincare',
        rating: 5,
        reviewCount: 88,
    },
    {
        id: 43243,
        name: "Maquillaje Eternal Glow SPF 25 Giordani Gold",
        brand: "Giordani Gold",
        price: 17.99,
        regularPrice: 32.00,
        imageUrl: `https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43243%2FES%2F43243_1.png`,
        description: "Base de maquillaje con serum que ilumina y perfecciona la piel al instante y a largo plazo. Con SPF 25 y Ácido Hialurónico para un acabado radiante y juvenil. Una fórmula híbrida que combina lo mejor del maquillaje y el cuidado de la piel.",
        howToUse: "Aplicar una pequeña cantidad en el centro del rostro y difuminar hacia el exterior con una brocha, esponja o con los dedos para un acabado uniforme.",
        stock: 40,
        category: 'makeup',
        productType: 'Base',
        subCategory: 'Giordani Gold',
        rating: 5,
        reviewCount: 953,
        variants: {
            Tono: [
                { value: 'Light Ivory', colorCode: '#F5E4D3' },
                { value: 'Porcelain', colorCode: '#F3D9C6' },
                { value: 'Warm Beige', colorCode: '#E4BFA8' },
                { value: 'Natural Sand', colorCode: '#D8AF92' },
                { value: 'Golden Sun', colorCode: '#C89A76' },
            ]
        }
    },
    {
        id: 104,
        name: "WellnessPack Mujer Wellosophy",
        brand: "Wellosophy",
        price: 45.00,
        imageUrl: `https://raw.githubusercontent.com/tmaromero/imagenes/main/29696.png`,
        description: "Cuida tu bienestar integral con WellnessPack Mujer de Wellosophy. Cada sobre diario te aporta una mezcla precisa de 12 vitaminas, 10 minerales, Omega-3 de alta calidad y potentes antioxidantes como la Astaxantina.",
        howToUse: "Tomar el contenido de un sobre al día con la comida principal y un vaso de agua.",
        stock: 20,
        category: 'wellness',
        rating: 5,
        reviewCount: 210,
    },
    {
        id: 103,
        name: "Pre-Champú Reparador Duologi",
        brand: "DUOLOGI",
        price: 13.00,
        imageUrl: `https://raw.githubusercontent.com/tmaromero/imagenes/main/44960.png`,
        description: "Transforma tu cabello con el Pre-Champú Reparador Duologi. Este tratamiento intensivo prelavado con Queratina y Lípidos de Avena, penetra en la fibra capilar para reparar y reducir el daño visible desde la primera aplicación.",
        howToUse: "Aplicar sobre el cabello seco antes de lavarlo, de medios a puntas. Dejar actuar 5 minutos. Aclarar y proceder con el champú y acondicionador.",
        stock: 25,
        category: 'hair',
        rating: 4,
        reviewCount: 45,
    },
    {
        id: 102,
        name: "Maquillaje Everlasting Sync SPF 20",
        brand: "THE ONE",
        price: 18.00,
        imageUrl: `https://raw.githubusercontent.com/tmaromero/imagenes/main/42128.png`,
        description: "Descubre el maquillaje inteligente que se sincroniza con tu piel. La Base Everlasting Sync SPF 20 de THE ONE, con Tecnología Skin Response, se adapta a la humedad del ambiente para un acabado fresco y semi-mate que dura hasta 30 horas.",
        howToUse: "Aplicar sobre la piel limpia e hidratada. Difuminar uniformemente desde el centro del rostro hacia el exterior con una brocha, esponja o la yema de los dedos.",
        stock: 30,
        category: 'makeup',
        productType: 'Base',
        subCategory: 'THE ONE',
        rating: 5,
        reviewCount: 150,
    },
    {
        id: 46901,
        name: "Perlas con Serum Giordani Gold - Edición Especial",
        brand: "Giordani Gold",
        price: 21.99,
        regularPrice: 35.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46901%2F46901_1.png",
        description: "Perlas de color con infusión de Sérum rejuvenecedor y Ácido Hialurónico que aportan color, rubor y luminosidad. Cada perla está formada por pigmentos minerales que crean un look natural y radiante. Edición especial con un diseño exclusivo.",
        howToUse: "Desliza la brocha sobre las perlas y aplica sobre los pómulos para un rubor saludable, en la frente y nariz para un efecto bronceado, o en el escote para un toque de luminosidad.",
        stock: 25,
        category: 'makeup',
        productType: 'Colorete y Bronceador',
        subCategory: 'Giordani Gold',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 1,
    },
    {
        id: 47828,
        name: "Brocha Blush & Glow",
        brand: "Vellaperfumeria",
        price: 6.49,
        regularPrice: 11.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47828%2F47828_1.png",
        description: "Brocha de maquillaje de alta calidad, perfecta para aplicar colorete e iluminador. Sus cerdas suaves y su forma angulada permiten una aplicación precisa y un acabado profesional y difuminado.",
        howToUse: "Utiliza la brocha para recoger el producto y aplícalo en los pómulos para dar color, o en los puntos altos del rostro (pómulos, puente de la nariz, arco de cupido) para iluminar.",
        stock: 50,
        category: 'accessories',
        productType: 'Accesorio de Maquillaje',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 86,
    },
    {
        id: 47949,
        name: "Máscara de Pestañas 5 en 1 Wonder Lash Prom Queen THE ONE",
        brand: "THE ONE",
        price: 6.99,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47949%2F47949_1.png",
        description: "La máscara de pestañas 5 en 1 definitiva, ahora en edición especial Prom Queen. Ofrece longitud, volumen, rizo, separación y cuidado en una sola pasada para una mirada de impacto.",
        howToUse: "Aplica desde la raíz hasta las puntas con un movimiento en zigzag para cubrir todas las pestañas. Aplica una segunda capa para mayor volumen e intensidad.",
        stock: 100,
        category: 'makeup',
        productType: 'Máscara',
        subCategory: 'THE ONE',
        rating: 5,
        reviewCount: 878,
    },
    {
        id: 46801,
        name: "Eau de Parfum Divine Dark Velvet",
        brand: "Divine",
        price: 27.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46801%2F46801_1.png",
        description: "Una fragancia Chipre Floral Amaderada que deja una estela hipnótica y duradera. Las notas de la flor Rubí Scurofloren son el corazón de este aroma sensual y misterioso, perfecto para la noche.",
        howToUse: "Vaporiza la fragancia en los puntos de pulso: cuello, escote y muñecas, para una mayor duración e intensidad.",
        stock: 30,
        category: 'perfume',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 26,
    },
    {
        id: 49145,
        name: "Collar Divine Dark Velvet",
        brand: "Divine",
        price: 29.99,
        regularPrice: 41.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F49145%2F49145_1.png",
        description: "Elegante collar de edición limitada inspirado en la fragancia Divine Dark Velvet. Un accesorio sofisticado con detalles en tonos oscuros y dorados para complementar tu look de noche.",
        howToUse: "Ajusta el largo a tu gusto y combínalo con tus prendas favoritas para un toque de elegancia.",
        stock: 15,
        category: 'accessories',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 1,
    },
    {
        id: 48075,
        name: "Muestra Eau de Parfum Divine Dark Velvet",
        brand: "Divine",
        price: 1.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48075%2F48075_1.png",
        description: "Descubre la nueva y cautivadora fragancia Divine Dark Velvet. Una muestra perfecta para probar su aroma Chipre Floral Amaderado y decidir si es tu nueva firma olfativa.",
        howToUse: "Aplicar una pequeña cantidad en la muñeca o en el cuello para experimentar la fragancia en tu piel.",
        stock: 100,
        category: 'perfume',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 0,
    },
    {
        id: 42041,
        name: "Spray Eau de Parfum Divine - Tamaño Viaje",
        brand: "Divine",
        price: 10.99,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42041%2F42041_1.png",
        description: "Tu fragancia Divine favorita en un práctico formato de viaje de 8 ml para que la lleves siempre contigo.",
        howToUse: "Vaporizar sobre los puntos de pulso (cuello, muñecas) siempre que desees reavivar la fragancia a lo largo del día.",
        stock: 50,
        category: 'perfume',
        rating: 5,
        reviewCount: 321,
    },
    {
        id: 47016,
        name: "Crema Corporal Perfumada Divine",
        brand: "Divine",
        price: 8.99,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47016%2F47016_1.png",
        description: "Una rica y suntuosa crema corporal que hidrata y nutre la piel en profundidad, dejándola irresistiblemente suave y perfumada con el icónico aroma floral de Divine.",
        howToUse: "Masajear generosamente sobre la piel limpia y seca, preferiblemente después de la ducha o el baño, para una hidratación duradera.",
        stock: 40,
        category: 'personal-care',
        rating: 5,
        reviewCount: 714,
    },
    {
        id: 38497,
        name: "Eau de Parfum Divine",
        brand: "Divine",
        price: 27.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38497%2FES%2F38497_1.png",
        description: "La fragancia floral original de Divine, un clásico atemporal que celebra la feminidad y el poder con sus notas de lirio y freesia. Un aroma que te hace sentir como una diosa.",
        howToUse: "Aplica la fragancia en el cuello, las muñecas y detrás de las orejas para una estela inolvidable que te acompañará todo el día.",
        stock: 35,
        category: 'perfume',
        rating: 5,
        reviewCount: 1953,
    },
    {
        id: 42120,
        name: "Máscara de Pestañas 5 en 1 Wonder Lash Waterproof THE ONE",
        brand: "THE ONE",
        price: 6.99,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42120%2F42120_1.png",
        description: "Todos los beneficios de la máscara 5 en 1, ahora con una fórmula resistente al agua. Ofrece longitud, volumen, rizo, separación y cuidado, con una duración impecable a prueba de agua, sudor y lágrimas.",
        howToUse: "Aplica desde la raíz hasta las puntas con un movimiento de zigzag. Para desmaquillar, utiliza un desmaquillante específico para productos waterproof.",
        stock: 80,
        category: 'makeup',
        productType: 'Máscara',
        subCategory: 'THE ONE',
        rating: 5,
        reviewCount: 841,
    },
    {
        id: 43123,
        name: "Máscara de Pestañas 5 en 1 Wonder Lash Ultra THE ONE",
        brand: "THE ONE",
        price: 6.99,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43123%2F43123_1.png",
        description: "Lleva tus pestañas al siguiente nivel con la máscara de pestañas Ultra. Una fórmula con HD Lash-Lifting Complex que proporciona un volumen, definición y curvatura extremos para un efecto lifting de pestañas al instante.",
        howToUse: "Usa el lado curvo del cepillo para levantar y rizar las pestañas. Usa el lado plano para dar volumen desde la raíz. Aplica varias capas para un efecto más dramático.",
        stock: 75,
        category: 'makeup',
        productType: 'Máscara',
        subCategory: 'THE ONE',
        rating: 5,
        reviewCount: 613,
    },
    {
        id: 46319,
        name: "Niacinamida 10% Power Drops Proceuticals Novage+",
        brand: "Novage+",
        price: 39.99,
        regularPrice: 57.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46319%2F46319_1.png",
        description: "Tratamiento concentrado con Niacinamida al 10% que minimiza visiblemente los poros, unifica el tono, reduce rojeces y fortalece la barrera cutánea. Una solución potente para una piel más lisa y saludable.",
        howToUse: "Aplicar unas gotas sobre la piel limpia antes del sérum. Usar por la mañana y/o por la noche. Evitar el contorno de ojos.",
        stock: 20,
        category: 'skincare',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 3,
    },
    {
        id: 47267,
        name: "Jabón Líquido con Flor de Loto y Madera de Cedro",
        brand: "Essense&Co.",
        price: 14.99,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47267%2F47267_1.png",
        description: "Lujoso jabón líquido para manos y cuerpo con una fragancia floral y amaderada. Limpia suavemente sin resecar, dejando la piel hidratada y delicadamente perfumada con notas de flor de loto y madera de cedro.",
        howToUse: "Aplicar sobre la piel húmeda, masajear hasta crear una rica espuma y aclarar con agua. Apto para uso diario.",
        stock: 60,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 141,
    },
    {
        id: 47268,
        name: "Loción Hidratante con Flor de Loto y Madera de Cedro",
        brand: "Essense&Co.",
        price: 15.99,
        regularPrice: 21.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47268%2F47268_1.png",
        description: "Una loción hidratante para manos y cuerpo de rápida absorción que deja la piel suave, nutrida y perfumada con el relajante aroma de flor de loto y madera de cedro.",
        howToUse: "Masajear sobre la piel limpia y seca hasta su completa absorción. Ideal para usar después del Jabón Líquido de la misma línea.",
        stock: 55,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 115,
    },
    {
        id: 153753,
        name: "Lote Essense & Co",
        brand: "Essense&Co.",
        price: 22.99,
        regularPrice: 41.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F153753%2F153753_1.png",
        description: "Un set de lujo para el cuidado de manos y cuerpo que incluye el jabón líquido y la loción hidratante de la línea Essense & Co. El regalo perfecto para una experiencia de spa en casa.",
        howToUse: "Utilizar el jabón líquido para limpiar la piel y seguir con la loción para hidratar y perfumar, creando una experiencia sensorial completa.",
        stock: 25,
        category: 'personal-care',
        tag: 'NOVEDAD',
        statusLabel: 'Set',
        rating: 5,
        reviewCount: 0,
    },
    {
        id: 18437,
        name: "Tratamiento Restaurador de Noche Diamond Cellular",
        brand: "Diamond Cellular",
        price: 24.99,
        regularPrice: 57.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F18437%2FES%2F18437_1.png",
        description: "Tratamiento de noche de alto rendimiento con Elixir de Diamante™ y Ácido Salicílico. Ayuda a regenerar, rejuvenecer y mejorar la superficie de la piel mientras duermes para un cutis más luminoso por la mañana.",
        howToUse: "Aplicar cada noche sobre la piel limpia del rostro y cuello, evitando el contorno de ojos. Masajear suavemente hasta su completa absorción.",
        stock: 30,
        category: 'skincare',
        rating: 5,
        reviewCount: 1327,
    },
    {
        id: 21339,
        name: "Solución Micelar Diamond Cellular",
        brand: "Diamond Cellular",
        price: 18.99,
        regularPrice: 29.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F21339%2FES%2F21339_1.png",
        description: "Un limpiador multifuncional de lujo. Elimina el maquillaje y las impurezas, tonifica y calma la piel en un solo paso. Con Elixir de Diamante™ y Tecnología Micelar para una piel limpia, fresca y radiante.",
        howToUse: "Aplicar sobre un disco de algodón y pasar suavemente por el rostro, ojos y labios por la mañana y por la noche. No necesita aclarado.",
        stock: 40,
        category: 'skincare',
        rating: 5,
        reviewCount: 1798,
    },
    {
        id: 13659,
        name: "Crema Antienvejecimiento Diamond Cellular",
        brand: "Diamond Cellular",
        price: 28.99,
        regularPrice: 57.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F13659%2FES%2F13659_1.png",
        description: "Crema de día de lujo que combate los signos del envejecimiento. Formulada con Elixir de Diamante™ y un complejo iluminador para una piel visiblemente más joven, firme y radiante.",
        howToUse: "Aplicar por la mañana sobre la piel limpia del rostro y cuello, evitando la zona de los ojos. Es una base perfecta para el maquillaje.",
        stock: 28,
        category: 'skincare',
        rating: 5,
        reviewCount: 3154,
    },
    {
        id: 47421,
        name: "Espátula de Crema Hidratante Oriflame Exklusiv",
        brand: "Oriflame Exklusiv",
        price: 5.29,
        regularPrice: 6.50,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47421%2F47421_1.png",
        description: "Una espátula higiénica y reutilizable para aplicar tus cremas faciales. Evita la contaminación del producto al no usar los dedos y permite una aplicación más precisa y uniforme.",
        howToUse: "Utiliza la espátula para coger una pequeña cantidad de tu crema y aplícala en el rostro. Limpiar después de cada uso con agua y jabón.",
        stock: 100,
        category: 'accessories',
        rating: 5,
        reviewCount: 473,
    },
    {
        id: 47005,
        name: "Crema de Día Reafirmante SPF 20 Royal Velvet",
        brand: "Royal Velvet",
        price: 20.99,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47005%2F47005_1.png",
        description: "Una fórmula avanzada con Infusión de Iris Negro™ que reafirma, redefine el contorno facial y reduce la apariencia de arrugas. Con SPF 20 para proteger la piel del fotoenvejecimiento.",
        howToUse: "Aplicar cada mañana sobre la piel limpia del rostro y cuello con un suave masaje ascendente.",
        stock: 35,
        category: 'skincare',
        rating: 5,
        reviewCount: 2161,
    },
    {
        id: 47006,
        name: "Crema de Noche Reafirmante Royal Velvet",
        brand: "Royal Velvet",
        price: 20.99,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47006%2F47006_1.png",
        description: "Trabaja durante la noche para nutrir, fortalecer y reafirmar la piel. La Infusión de Iris Negro™ ayuda a la piel en su proceso de regeneración nocturna, reduciendo la apariencia de arrugas.",
        howToUse: "Aplicar cada noche sobre la piel limpia del rostro y cuello, después del sérum, para potenciar la reparación nocturna.",
        stock: 32,
        category: 'skincare',
        rating: 5,
        reviewCount: 1781,
    },
    {
        id: 47587,
        name: "Pendientes Royal Velvet",
        brand: "Royal Velvet",
        price: 16.99,
        regularPrice: 22.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47587%2F47587_1.png",
        description: "Elegantes pendientes de edición limitada que complementan la lujosa línea de cuidado de la piel Royal Velvet. Un toque final de sofisticación para cualquier look.",
        howToUse: "Accesorio de moda para llevar en las orejas. Evitar el contacto con agua y perfumes para mantener su brillo.",
        stock: 20,
        category: 'accessories',
        rating: 4.5,
        reviewCount: 19,
    }
];