
import type { Product } from './ProductCard';

export const allProducts: Product[] = [
    // Existing products from previous OfertasPage, with updated images
    {
        id: 101,
        name: "Bálsamo BB Cream OnColour",
        brand: "OnColour",
        price: 0.5,
        regularPrice: 5.00,
        imageUrl: "https://i.imgur.com/k6r5k3L.png",
        description: "Descubre la perfección 8 en 1. Nuestro Bálsamo BB Cream con SPF 10 no solo hidrata y unifica el tono de tu piel, sino que también la protege del sol. Su fórmula ligera se funde a la perfección para un acabado radiante y natural, disimulando imperfecciones y dejando un aspecto fresco durante todo el día. El imprescindible para tu rutina diaria.",
        stock: 50,
        category: 'makeup',
        subCategory: 'OnColour',
        rating: 4,
        reviewCount: 88,
        isShippingSaver: true,
    },
    {
        id: 102,
        name: "Maquillaje Everlasting Sync SPF 20",
        brand: "THE ONE",
        price: 5.67,
        regularPrice: 15.00,
        imageUrl: "https://i.imgur.com/gKj3a5T.png",
        description: "Experimenta una base de maquillaje inteligente que se adapta a ti. Everlasting Sync con SPF 20 y Tecnología Skin Response se sincroniza con la humedad del ambiente para mantener tu piel fresca y equilibrada. Disfruta de una cobertura media-alta modulable, un acabado semi-mate de larga duración y protección UVA. ¡Luce una piel perfecta sin esfuerzo durante 30 horas!",
        stock: 30,
        category: 'makeup',
        subCategory: 'THE ONE',
        rating: 5,
        reviewCount: 150,
    },
    {
        id: 103,
        name: "Pre-Champú Reparador Duologi",
        brand: "DUOLOGI",
        price: 0.82,
        regularPrice: 10.00,
        imageUrl: "https://i.imgur.com/eO3XW3h.png",
        description: "Revoluciona tu cuidado capilar con nuestro Pre-Champú Reparador. Este tratamiento prelavado de lujo está formulado para reparar la fibra capilar y reducir visiblemente el daño desde el primer uso. Fortalece, protege y restaura tu cabello antes del champú, preparándolo para un acabado que se siente nuevo y saludable. Fórmula sin parabenos ni siliconas para un cuidado puro y efectivo.",
        stock: 25,
        category: 'hair',
        rating: 4,
        reviewCount: 45,
    },
    {
        id: 104,
        name: "WellnessPack Mujer Wellosophy",
        brand: "Wellosophy",
        price: 29.99,
        regularPrice: 42.00,
        imageUrl: "https://i.imgur.com/mF4H2zS.png",
        description: "Potencia tu bienestar diario desde dentro con WellnessPack Mujer. Cada sobre contiene una combinación experta de 12 vitaminas y 10 minerales, ácidos grasos Omega-3 de alta calidad procedentes de aceite de pescado sostenible y potentes antioxidantes, incluyendo la Astaxantina. Diseñado para cubrir las necesidades nutricionales de la mujer, apoya la belleza de la piel, la energía y el sistema inmunitario.",
        stock: 20,
        category: 'wellness',
        rating: 5,
        reviewCount: 210,
    },
    {
        id: 105,
        name: "Crema de Noche Reafirmante Royal Velvet",
        brand: "Royal Velvet",
        price: 13.68,
        regularPrice: 37.00,
        imageUrl: "https://i.imgur.com/DqG7K2r.png",
        description: "Despierta con una piel visiblemente más firme y rejuvenecida. Nuestra Crema de Noche Reafirmante Royal Velvet, enriquecida con la exclusiva Infusión de Iris Negro, trabaja mientras duermes para fortalecer la estructura de la piel, mejorar la elasticidad y renovar el colágeno. Una experiencia nocturna de lujo para un contorno facial más definido.",
        stock: 15,
        category: 'skincare',
        rating: 5,
        reviewCount: 95,
    },
    {
        id: 106,
        name: "Eau de Parfum Love Potion",
        brand: "Oriflame",
        price: 16.35,
        regularPrice: 38.00,
        imageUrl: "https://i.imgur.com/mP7G6xY.png",
        description: "Desata tu poder de seducción con Love Potion. Una fragancia oriental y avainillada que explora el arte del amor. Sus notas afrodisíacas de jengibre espeziado, flor de cacao y un toque de chocolate se entrelazan para crear una estela irresistible. El elixir perfecto para momentos inolvidables.",
        stock: 18,
        category: 'perfume',
        rating: 4,
        reviewCount: 123,
    },
    {
        id: 107,
        name: "Mascarilla Nocturna Novage+",
        brand: "NOVAGE+",
        price: 12.79,
        regularPrice: 34.00,
        imageUrl: "https://i.imgur.com/x5M7y5F.png",
        description: "Dale a tu piel un respiro y una recarga de hidratación intensa durante la noche. La Mascarilla Nocturna Novage+ está formulada con Ácido Hialurónico y nutritivo aceite Inca Inchi para borrar los signos de fatiga, fortalecer la barrera cutánea y restaurar la luminosidad. Despierta con un rostro visiblemente más descansado, suave y radiante.",
        stock: 22,
        category: 'skincare',
        rating: 5,
        reviewCount: 78,
    },
    {
        id: 108,
        name: "Polvos Compactos con Serum Giordani Gold",
        brand: "GIORDANI GOLD",
        price: 12.79,
        regularPrice: 21.00,
        imageUrl: "https://i.imgur.com/Z4c9e4V.png",
        description: "Más que un maquillaje, un tratamiento para tu piel. Los Polvos Compactos Giordani Gold fusionan un color de alta definición con un potente Serum Rejuvenecedor. Enriquecidos con Ácido Hialurónico hidratante y Extracto de Peonía Blanca, perfeccionan la tez mientras la cuidan. Incluyen Filtro Solar SPF para una protección diaria. El toque final para un acabado sedoso y luminoso.",
        stock: 35,
        category: 'makeup',
        subCategory: 'Giordani Gold',
        rating: 4,
        reviewCount: 65,
    },
    {
        id: 109,
        name: "Crema Reparadora Talones Agrietados Feet Up",
        brand: "Feet Up Expert",
        price: 1.22,
        regularPrice: 10.00,
        imageUrl: "https://i.imgur.com/mY77z9U.png",
        description: "¡Resultados visibles en 3 días! Esta crema de acción intensiva con Urea al 10%, tecnología Pro-Barrier y Empeline, repara e hidrata los talones agrietados. Clínicamente probada, restaura la suavidad y protege la barrera de la piel para unos pies sanos y bonitos.",
        stock: 40,
        category: 'personal-care',
        rating: 5,
        reviewCount: 195,
        isShippingSaver: true,
    },
     {
        id: 110,
        name: "Acondicionador Suavizante Miel y Leche",
        brand: "Milk & Honey Gold",
        price: 1.99,
        regularPrice: 8.00,
        imageUrl: "https://i.imgur.com/a4gY5qB.jpg",
        description: "Un acondicionador lujoso y cremoso para las pieles más delicadas. Enriquecido con extractos orgánicos de leche y miel, nutre y regenera en profundidad. Calma, suaviza y alivia picores, siendo ideal para cabello seco y pieles con condiciones como dermatitis o psoriasis.",
        stock: 30,
        category: 'hair',
        rating: 4,
        reviewCount: 77,
    },
    {
        id: 111,
        name: "Champú Suavizante Miel y Leche",
        brand: "Milk & Honey Gold",
        price: 1.99,
        regularPrice: 8.00,
        imageUrl: "https://i.imgur.com/8O8L0rG.jpg",
        description: "Limpia y nutre tu cabello con este champú rico e hidratante. Su fórmula con extractos orgánicos de leche y miel es súper hidratante, regenera, calma y suaviza. Perfecto para el cabello seco y el cuidado de pieles delicadas, aliviando condiciones como la piel atópica o la psoriasis.",
        stock: 30,
        category: 'hair',
        rating: 4,
        reviewCount: 82,
    },
    {
        id: 112,
        name: "Champú Matizador Duologi",
        brand: "DUOLOGI",
        price: 6.99,
        regularPrice: 14.00,
        imageUrl: "https://i.imgur.com/pU2R6hF.png",
        description: "Neutraliza los tonos anaranjados y amarillentos no deseados en cabellos rubios y con mechas. Este champú con pigmentos violetas y Aminoácidos de Seda revitaliza el color, dejándolo brillante, suave y sin tonos cobrizos. ¡Consigue el rubio perfecto!",
        stock: 20,
        category: 'hair',
        rating: 5,
        reviewCount: 35,
    },
    // New products from images
    {
        id: 201,
        name: "Eau de Parfum Eclat Nuit para Ella",
        brand: "Eclat",
        price: 24.99,
        regularPrice: 43.00,
        imageUrl: "https://i.imgur.com/jI8fK1M.jpg",
        description: "Sumérgete en la noche parisina con Eclat Nuit. Un Chipre floral cautivador con notas de pachulí, rosa y jazmín que dejan una estela intensa y sofisticada. El aroma perfecto para una mujer elegante y misteriosa.",
        stock: 25,
        category: 'perfume',
        rating: 5,
        reviewCount: 40,
    },
    {
        id: 202,
        name: "Limpiador en Aceite Novage+",
        brand: "NOVAGE+",
        price: 19.99,
        regularPrice: 30.00,
        imageUrl: "https://i.imgur.com/Y3g1A5D.jpg",
        description: "Transforma tu rutina de limpieza. Este lujoso aceite limpiador se convierte en una emulsión lechosa al contacto con el agua, disolviendo eficazmente el maquillaje, el protector solar y las impurezas sin resecar. Su sistema Bio Lipid nutre y reconforta la piel, dejándola suave, limpia y radiante.",
        stock: 30,
        category: 'skincare',
        rating: 5,
        reviewCount: 60,
    },
    {
        id: 203,
        name: "Mascarilla y Exfoliante 2 en 1 Love Nature",
        brand: "Love Nature",
        price: 2.99,
        regularPrice: 7.00,
        imageUrl: "https://i.imgur.com/bW3g1Tq.jpg",
        description: "Un tratamiento dual para pieles grasas. Enriquecido con árbol de té y lima orgánicos, esta mascarilla y exfoliante purifica profundamente, controla el exceso de sebo y minimiza los poros. Úsalo como mascarilla para purificar o como exfoliante para una piel suave y sin brillos.",
        stock: 45,
        category: 'skincare',
        rating: 4,
        reviewCount: 110,
    },
    {
        id: 204,
        name: "Sérum Antiarrugas Novage+",
        brand: "NOVAGE+",
        price: 40.00,
        regularPrice: 60.00,
        imageUrl: "https://i.imgur.com/n6t3f4o.jpg",
        description: "Desafía las arrugas con este potente sérum. Formulado con tecnología Bio CollagenPro y Orpéptido-3, estimula la producción de colágeno para reducir visiblemente las líneas de expresión y arrugas. Una piel más lisa, firme y de aspecto rejuvenecido.",
        stock: 20,
        category: 'skincare',
        rating: 5,
        reviewCount: 85,
    },
    {
        id: 205,
        name: "Desodorante Roll-On Perfumado Miss Giordani",
        brand: "Giordani Gold",
        price: 0.99,
        regularPrice: 5.00,
        imageUrl: "https://i.imgur.com/R3x3f6o.jpg",
        description: "Mantén la frescura y la confianza todo el día con el vibrante aroma de Miss Giordani. Este desodorante roll-on ofrece una protección eficaz mientras te envuelve en las chispeantes notas de neroli, mango y pimienta rosa.",
        stock: 50,
        category: 'personal-care',
        rating: 4,
        reviewCount: 92,
        isShippingSaver: true,
    },
    {
        id: 206,
        name: "Aceite Facial Purificante Love Nature",
        brand: "Love Nature",
        price: 3.99,
        regularPrice: 9.00,
        imageUrl: "https://i.imgur.com/tL7q2qU.jpg",
        description: "El secreto para una piel grasa equilibrada. Este aceite facial ligero con árbol de té y lima orgánicos purifica, calma las imperfecciones y ayuda a controlar el exceso de grasa sin obstruir los poros. Unas pocas gotas para una piel más clara y confortable.",
        stock: 35,
        category: 'skincare',
        rating: 4,
        reviewCount: 75,
    },
    {
        id: 207,
        name: "Champú Anticaída Duologi",
        brand: "DUOLOGI",
        price: 6.99,
        regularPrice: 13.00,
        imageUrl: "https://i.imgur.com/WbV1P4Q.png",
        description: "Fortalece tu cabello desde la raíz. Este champú anticaída está formulado con péptidos de arroz y vitamina B3 para nutrir el cuero cabelludo, reducir la caída del cabello y promover un crecimiento más fuerte y saludable. Para un cabello visiblemente más denso y resistente.",
        stock: 28,
        category: 'hair',
        rating: 5,
        reviewCount: 55,
    },
    {
        id: 208,
        name: "Crema Corporal Giordani Gold Essenza Supreme",
        brand: "Giordani Gold",
        price: 7.99,
        regularPrice: 15.00,
        imageUrl: "https://i.imgur.com/eP6p7xQ.png",
        description: "Envuelve tu piel en un velo de lujo. Esta crema corporal intensamente nutritiva hidrata en profundidad mientras te perfuma con la radiante y sofisticada fragancia de Giordani Gold Essenza Supreme. Una piel suave, luminosa y exquisitamente perfumada.",
        stock: 22,
        category: 'personal-care',
        rating: 5,
        reviewCount: 68,
    },
    {
        id: 209,
        name: "Crema Corporal Perfumada Possess",
        brand: "Possess",
        price: 7.99,
        regularPrice: 15.00,
        imageUrl: "https://i.imgur.com/uR7xP1d.png",
        description: "Despierta a tu Cleopatra interior con esta suntuosa crema corporal. Hidrata y suaviza la piel, dejándola irresistiblemente perfumada con las notas seductoras y atemporales de ylang ylang de la fragancia Possess.",
        stock: 19,
        category: 'personal-care',
        rating: 5,
        reviewCount: 71,
    },
    {
        id: 210,
        name: "Spray Protector del Calor Duologi",
        brand: "DUOLOGI",
        price: 4.99,
        regularPrice: 11.00,
        imageUrl: "https://i.imgur.com/cK2rG9v.png",
        description: "Tu escudo indispensable contra el calor. Este spray ligero protege tu cabello del daño causado por herramientas térmicas hasta 230°C. Formulado con queratina y lípidos de avena, deja el cabello suave, brillante y protegido sin apelmazar.",
        stock: 40,
        category: 'hair',
        rating: 4,
        reviewCount: 48,
    },
    {
        id: 211,
        name: "Mascarilla Capilar Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 5.99,
        regularPrice: 13.00,
        imageUrl: "https://i.imgur.com/mO4P0xL.png",
        description: "Un tratamiento intensivo para un cabello radiante. Esta mascarilla capilar, rica en extractos orgánicos de leche y miel, nutre en profundidad, restaura la suavidad y devuelve el brillo al cabello seco y dañado. Un capricho de lujo para una melena espectacular.",
        stock: 33,
        category: 'hair',
        rating: 5,
        reviewCount: 102,
    },
    {
        id: 212,
        name: "Labial Líquido Irresistible Touch High Shine THE ONE",
        brand: "THE ONE",
        price: 3.99,
        regularPrice: 9.00,
        imageUrl: "https://i.imgur.com/uG5D5uT.png",
        description: "Color y cuidado en uno. Este aceite labial nutritivo hidrata y suaviza los labios al instante, aportando un toque de color brillante y jugoso. Su fórmula no pegajosa se desliza suavemente para unos labios irresistibles.",
        stock: 60,
        category: 'makeup',
        subCategory: 'THE ONE',
        rating: 4,
        reviewCount: 99,
        variants: {
            Color: [
                { value: 'Sweet Rosewood', colorCode: '#A45D63', imageUrl: "https://i.imgur.com/uG5D5uT.png" },
                { value: 'Magnetic Red', colorCode: '#B92B3F' },
                { value: 'Chic Burgundy', colorCode: '#6E2636' },
                { value: 'Trendy Crimson', colorCode: '#D43744' },
            ],
        },
    },
    {
        id: 213,
        name: "Sérum Urban Guard 3D Optimals",
        brand: "Optimals",
        price: 10.99,
        regularPrice: 20.00,
        imageUrl: "https://i.imgur.com/8QpJRiP.png",
        description: "Protege tu piel de las agresiones urbanas. Este sérum concentrado con tecnología Urban3Rescuer, pantenol y ácido hialurónico, hidrata, fortalece la barrera cutánea y defiende la piel de la contaminación. Para una piel fresca, equilibrada y resistente.",
        stock: 25,
        category: 'skincare',
        rating: 4,
        reviewCount: 58,
    },
    {
        id: 214,
        name: "Lote Experto Antienvejecimiento Novage+",
        brand: "NOVAGE+",
        price: 154.00,
        regularPrice: 225.00,
        imageUrl: "https://i.imgur.com/m4w2j2B.png",
        description: "La rutina completa para combatir los signos del envejecimiento. Este lote experto de Novage+ incluye limpiador, contorno de ojos, sérum, y cremas de día y noche para una piel visiblemente más firme, lisa y luminosa. Resultados clínicamente probados.",
        stock: 15,
        category: 'skincare',
        tag: 'SET',
        rating: 5,
        reviewCount: 130,
    },
    {
        id: 215,
        name: "Aceite Protector para el Cabello Eleo",
        brand: "Eleo",
        price: 9.99,
        regularPrice: 19.00,
        imageUrl: "https://i.imgur.com/YqT4K2f.png",
        description: "Un elixir de belleza para tu cabello. Este aceite protector, enriquecido con aceite de Marula y 6 aceites preciosos, nutre, repara y protege el cabello, dejándolo increíblemente suave, manejable y lleno de brillo. Ideal para todo tipo de cabello.",
        stock: 38,
        category: 'hair',
        rating: 5,
        reviewCount: 96,
    },
    {
        id: 216,
        name: "Mascarilla Reparación Intensa Duologi",
        brand: "DUOLOGI",
        price: 6.99,
        regularPrice: 13.00,
        imageUrl: "https://i.imgur.com/Zk9i3N7.png",
        description: "La solución definitiva para el cabello dañado. Esta mascarilla de reparación intensa, con queratina y lípidos de avena, penetra en la fibra capilar para reconstruir, fortalecer y proteger contra la rotura. Devuelve la vida a tu cabello en minutos.",
        stock: 26,
        category: 'hair',
        rating: 5,
        reviewCount: 73,
    },
    {
        id: 217,
        name: "Eau de Toilette Eclat Homme Weekend Azur",
        brand: "Eclat",
        price: 23.99,
        regularPrice: 41.00,
        imageUrl: "https://i.imgur.com/YVpQ2Bk.jpg",
        description: "Captura la esencia de la Riviera Francesa. Una fragancia acuática y aromática para el hombre que disfruta de la libertad. Notas de bergamota, lavanda marina y ámbar gris crean un aroma fresco, elegante y revitalizante.",
        stock: 21,
        category: 'men',
        rating: 4,
        reviewCount: 39,
    },
    {
        id: 218,
        name: "Crema Definidora de Rizos Duologi",
        brand: "DUOLOGI",
        price: 5.99,
        regularPrice: 12.00,
        imageUrl: "https://i.imgur.com/zB1J9Q8.png",
        description: "Define y controla tus rizos. Esta crema sin aclarado, enriquecida con manteca de karité y escualano, hidrata, combate el encrespamiento y define los rizos, dejándolos suaves, elásticos y llenos de vida. Para rizos perfectos todo el día.",
        stock: 31,
        category: 'hair',
        rating: 4,
        reviewCount: 44,
    },
    // ---- ADDED PRODUCTS ----
    {
        id: 301,
        name: "Cepillo Desenredante Styler PRO",
        brand: "Styler",
        price: 6.49,
        regularPrice: 9.00,
        imageUrl: "https://i.imgur.com/A6j4Y2P.png",
        description: "Desenreda tu cabello sin esfuerzo y sin tirones. Este cepillo es ideal para todo tipo de cabello, húmedo o seco. Sus cerdas flexibles se deslizan suavemente, protegiendo contra la rotura y dejando el cabello suave y manejable.",
        stock: 50,
        category: 'accessories',
        rating: 5,
        reviewCount: 112,
    },
    {
        id: 302,
        name: "Champú Purificante Duologi",
        brand: "DUOLOGI",
        price: 6.99,
        regularPrice: 13.00,
        imageUrl: "https://i.imgur.com/7vjP5dZ.png",
        description: "Limpia en profundidad el cuero cabelludo y el cabello. Formulado para eliminar el exceso de sebo, la caspa y las impurezas, dejando una sensación de frescor y ligereza. Ideal para cabellos con tendencia grasa.",
        stock: 30,
        category: 'hair',
        rating: 4,
        reviewCount: 63,
    },
    {
        id: 303,
        name: "Champú Reparación Intensa Duologi",
        brand: "DUOLOGI",
        price: 6.99,
        regularPrice: 13.00,
        imageUrl: "https://i.imgur.com/uX88g9L.png",
        description: "Devuelve la vida al cabello dañado. Este champú nutritivo con queratina y lípidos de avena repara y fortalece la fibra capilar desde el interior, reduciendo la rotura y mejorando la elasticidad.",
        stock: 25,
        category: 'hair',
        rating: 5,
        reviewCount: 88,
    },
    {
        id: 304,
        name: "Sérum Nocturno Reparador Duologi",
        brand: "DUOLOGI",
        price: 9.99,
        regularPrice: 13.00,
        imageUrl: "https://i.imgur.com/8Qp4z7p.png",
        description: "Un tratamiento intensivo que trabaja mientras duermes. Este sérum nocturno repara las puntas abiertas y nutre el cabello en profundidad, para que te despiertes con una melena más suave, fuerte y revitalizada.",
        stock: 20,
        category: 'hair',
        rating: 5,
        reviewCount: 51,
    },
    {
        id: 305,
        name: "Corrector en Stick OnColour",
        brand: "OnColour",
        price: 2.99,
        regularPrice: 6.00,
        imageUrl: "https://i.imgur.com/r6E7h7R.png",
        description: "Cubre imperfecciones al instante con este práctico corrector en stick. Su fórmula cremosa se difumina fácilmente para un acabado natural. Perfecto para llevar en el bolso y retocar en cualquier momento.",
        stock: 40,
        category: 'makeup',
        subCategory: 'OnColour',
        rating: 4,
        reviewCount: 76,
        variants: {
            Tono: [
                { value: 'Light' },
                { value: 'Medium' },
            ],
        },
    },
    {
        id: 306,
        name: "Crema de Manos y Cuerpo Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 6.99,
        regularPrice: 12.00,
        imageUrl: "https://i.imgur.com/hG9c4Uq.png",
        description: "Nutrición y lujo para tu piel. Esta crema ultra-hidratante, con extractos orgánicos de leche y miel, deja la piel de manos y cuerpo intensamente suave, nutrida y delicadamente perfumada. Un clásico indispensable.",
        stock: 35,
        category: 'personal-care',
        rating: 5,
        reviewCount: 250,
    },
    {
        id: 307,
        name: "Sérum Iluminador Antimanchas Novage+",
        brand: "NOVAGE+",
        price: 32.99,
        regularPrice: 47.00,
        imageUrl: "https://i.imgur.com/f8z7b6x.png",
        description: "Combate las manchas y recupera la luminosidad. Este sérum avanzado actúa sobre la hiperpigmentación, unifica el tono de la piel y le devuelve un aspecto radiante y juvenil. Para una tez visiblemente más clara y uniforme.",
        stock: 18,
        category: 'skincare',
        rating: 5,
        reviewCount: 93,
    },
    {
        id: 308,
        name: "Eau de Toilette Eclat Femme Weekend",
        brand: "Eclat",
        price: 27.99,
        regularPrice: 41.00,
        imageUrl: "https://i.imgur.com/4gS1d9Y.png",
        description: "La esencia de la elegancia espontánea. Una fragancia floral y afrutada con notas de melocotón de viña, fresia blanca y almizcle. Perfecta para la mujer que disfruta de la vida con un toque de sofisticación francesa.",
        stock: 22,
        category: 'perfume',
        rating: 4,
        reviewCount: 67,
    },
    {
        id: 309,
        name: "Lote de Día y Noche Rich Novage+",
        brand: "NOVAGE+",
        price: 47.99,
        regularPrice: 73.00,
        imageUrl: "https://i.imgur.com/XwF2n2H.png",
        description: "El dúo perfecto para una piel nutrida y protegida 24/7. La Crema de Día Rich con SPF 30 protege de las agresiones, mientras que la Crema de Noche Rich repara y regenera. Ambas formuladas para pieles que necesitan un extra de confort.",
        stock: 15,
        category: 'skincare',
        tag: 'SET',
        rating: 5,
        reviewCount: 45,
    },
    {
        id: 310,
        name: "Sérum Capilar Sellador Duologi",
        brand: "DUOLOGI",
        price: 9.99,
        regularPrice: 14.00,
        imageUrl: "https://i.imgur.com/9v8N7mY.png",
        description: "El toque final para un cabello perfecto. Este sérum ligero sella las puntas abiertas, controla el encrespamiento y aporta un brillo espectacular sin engrasar. Tu aliado para una melena suave y pulida.",
        stock: 30,
        category: 'hair',
        rating: 4,
        reviewCount: 59,
    },
    {
        id: 47828,
        name: "Brocha Blush & Glow",
        brand: "GIORDANI GOLD",
        price: 1.49,
        regularPrice: 6.00,
        imageUrl: "https://i.imgur.com/T0bSg0B.png",
        description: "Brocha para colorete y iluminador fabricada con PBT, aluminio y madera. Tamaño: 16cm.",
        stock: 50,
        category: 'accessories',
        isShippingSaver: true,
    },
];